name: wasm_worker
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.5.2

dependencies: 
  fetch_api: ^2.2.0
  rfw: ^1.0.29
  json: ^0.20.2
  shared:
    path: ../shared

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
