name: wasm_worker
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.2

# Add regular dependencies here.
dependencies: 
  # macros: any
  fetch_api: ^2.2.0
  rfw: ^1.0.29
  # freezed: ^3.0.0-0.0.dev
  json: ^0.20.2
  # shelf_router: ^1.1.4
  # dio: ^5.7.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
