name: store_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  rfw: ^1.0.29
  flutter_hooks: ^0.20.5
  riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  dio: ^5.7.0
  shared:
    path: ../shared
  youtube_player_flutter: ^9.1.1
  go_router: ^14.4.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.13
  freezed: ^2.5.7

flutter:

  uses-material-design: true
  assets:
    - assets/
